version: "3.8"
services:
  etl:
    build: ./etl/
  api:
    build: ./api/
    command: python src/app.py
    # volumes:
    #   - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    # env_file:
    #   - ./.env.dev
    depends_on:
      - db
  db:
    build: ./db/