version: "3.8"
services:
  etl:
    build: ./etl/
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./etl:/code/
  api:
    build: ./api/
    command: python src/app.py
    volumes:
      - ./api:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      etl:
        condition: service_completed_successfully
  db:
    build: ./db/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5